# AUTOGENERATED
if (TARGET libcorefungi::libcorefungi)
  return()
endif()
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}"
  "${CMAKE_BINARY_DIR}/packages/libcorefungi" EXCLUDE_FROM_ALL)
message(STATUS "Found libcorefungi ${libcorefungi_VERSION} (source)")
